# Generated by Django 4.1.7 on 2023-03-19 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_users_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
